services:
  - type: web
    name: mysite
    plan: free
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          type: redis
          name: mysite-cache
          property: connectionString

  - type: worker
    name: mysite-worker
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runworker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: mysite-cache
          property: connectionString

  - type: cron
    name: mysite-cron
    region: singapore
    runtime: python
    buildCommand: "./build.sh"
    schedule: "0 0 * * *"
    startCommand: "python manage.py runcrons"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: mysite-cache
          property: connectionString

  - type: redis
    name: mysite-cache
    region: singapore
    plan: free
    ipAllowList: []

  - type: pserv
    name: mysitedb
    region: singapore
    plan: free
    ipAllowList: []
