# Generated by Django 5.0.1 on 2025-01-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_user_youtube_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '評価カテゴリ',
                'verbose_name_plural': '評価カテゴリ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='homepage.evaluationcategory')),
            ],
            options={
                'verbose_name': '評価サブカテゴリ',
                'verbose_name_plural': '評価サブカテゴリ',
                'ordering': ['category', 'order'],
            },
        ),
    ]
